import type { Metadata } from "next";
import localFont from "next/font/local";

import "../globals.css"
import { ThemeProvider } from "./context/ThemeContext";
import ClientThemeWrapper from "./context/clientThemeWrapper";
import Header from "../components/Header";
import BottomTab from "../components/UI/BottomTab";
import SideBar from "../components/SideBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <ClientThemeWrapper>
              <div className="flex flex-col h-screen">
                <Header />

                <div className="flex flex-1 overflow-hidden">
                  <SideBar />
                  <main className="flex-1 overflow-auto">
                    {children}
                  </main>
                  <BottomTab />
                </div>
              </div>
          </ClientThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}